### ISSUE TITLE
Documentation Request: Add `raises` to increase Nif Safety

### ISSUE THREAD

**Issue by elcritch** [wltsmrz/nimler#15]
It seems like Nim can check exceptions which would be a nice bit of extra safety. Changing the `add_numbers` example to not check the decoded values will throw a Nim exception that crashes BEAM: 

```nim
proc add_numbers(env: ptr ErlNifEnv, argc: cint, argv: ErlNifArgs): ErlNifTerm =
  let a1 = argv[0].decode(env, int32).get()
  let a2 = argv[1].decode(env, int32).get()
  let r = a1 + a2
  return r.encode(env)
```

However this can be checked by adding `{.raises: [].}` pragma to ensure you handle possible exceptions: 

```nim
proc add_numbers(env: ptr ErlNifEnv, argc: cint, argv: ErlNifArgs): ErlNifTerm {.raises: [].} =
  let a1 = argv[0].decode(env, int32).get()
  let a2 = argv[1].decode(env, int32).get()
  let r = a1 + a2
  return r.encode(env)
```

Figure adding that to the docs would help people looking into Nim for NIF's as it increases BEAM safety. 

Also, would it be possible to make a template for setting up the load/unload things for using resources? It seems like that'd be the other major part that's easy to mess up. Having pre-made templates for the common case of setting up the resource_type would could be handy.

**Comment by wltsmrz** [comment]
> Figure adding that to the docs would help people looking into Nim for NIF's as it increases BEAM safety.

Good idea. I'll update the docs site

> Also, would it be possible to make a template for setting up the load/unload things for using resources?

I think it could be made simpler at least. Another good idea; I'll leave this issue open so I don't forget

**Comment by wltsmrz** [comment]
Here is the first pass if you want to take a look @elcritch https://github.com/wltsmrz/nimler/blob/resources/tests/init_resource/nif.nim

**Comment by elcritch** [comment]
Nice! I've never dealt with resources in a nif myself; just read the examples. Those look correct mostly. In Nim, would it be better to put those proc's into a macro or as a class? Mainly I think a default impl would just need to set one or more resource types.

**Comment by elcritch** [comment]
P.S. what about the "load"/"reload" actions? 

```c
static ErlNifFunc funcs[] = {
    {"parse_address", 1, parse_address}};

static int
load(ErlNifEnv *env, void **priv, ERL_NIF_TERM info) {}

static int
reload(ErlNifEnv *env, void **priv, ERL_NIF_TERM info) {}

static int
upgrade(ErlNifEnv *env, void **priv, void **old_priv, ERL_NIF_TERM info) {}

static void
unload(ErlNifEnv *env, void *priv) {}

ERL_NIF_INIT(Elixir.Expostal.Parser, funcs, &load, &reload, &upgrade, &unload)
```

**Comment by wltsmrz** [comment]
The way the docs read to me is that we only need to support `load` and `unload` although I'm not 100% sure that load will be called in the absence of upgrade. From what I've seen NIFs in the wild seem to call into their load() function from upgrade() anyway.

> load, upgrade and unload are pointers to functions. One of load or upgrade is called to initialize the library. unload is called to release the library. All are described individually below.
>
> The fourth argument NULL is ignored. It was earlier used for the deprecated reload callback which is no longer supported since OTP 20.

**Comment by elcritch** [comment]
Good to know the "reload" is deprecated. That simplifies it. The upgrade probably makes sense in terms of hot-code updates where the code would need to "upgrade" the resource. That seems pretty rare, for a default maybe document that "upgrade" defaults to "load". Then custom "upgrade" logic could just override the "upgrade" function handler if they want custom logic.
