### ISSUE TITLE
Fails to compile on macOS

### ISSUE THREAD

**Issue by walkr** [wltsmrz/nimler#20]
Hello,

I'm trying out this library on a macOS machine, but it fails to compile with the following error:

```
..Undefined symbols for architecture arm64:
  "_enif_get_long", referenced from:
      _zadd__nndM4hYgRfGl9btf9aujCMog in @mnif.nim.c.o
  "_enif_make_long", referenced from:
      _zadd__nndM4hYgRfGl9btf9aujCMog in @mnif.nim.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Nim Version:
```
Nim Compiler Version 1.4.8 [MacOSX: arm64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise
```

Elixir Version:
```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

IEx 1.12.3 (compiled with Erlang/OTP 24)
```
Any thoughts?

Thank you!

**Comment by isaacdonaldson** [comment]
I had the same problem as you did, I managed to fix it without needing a library patch. This is the nim forum post with the solution https://forum.nim-lang.org/t/8908. 

You have to pass linker flags --passL:'-undefined dynamic_lookup' that allows you to compile and lookup those missing symbols at runtime. 

You then have to compile a dylib for arm64 (and/or x86) and use that as the shared lib. These compiling lines are found in the nimble task in the attached forum post. `lipo` is used to combine the x86 and arm64 together into one dylib. This step might not be required for you but it was for me. 

Hope this helps you 😀

**Comment by walkr** [comment]
Yes, it definitely helped.

I edited `nim.cfg` and appended `passL:"-undefined dynamic_lookup"`.

I also had to append `out:"MY-LIB-NAME.dylib.so"` since it kept looking for a `*.so` file. 
It doesn't seem to recognize the difference in dynamic library naming between Linux and macOS platforms.

Thank you for taking the time to reply.
